export const GAME_ACTIONS = {
	NEXT_PHASE: 'NEXT_PHASE',
	NEXT_LEVEL: 'NEXT_LEVEL',
	DECREMENT_TIME: 'DECREMENT_TIME',
	GAME_OVER: 'GAME_OVER',
	INCREMENT_ERRORS: 'INCREMENT_ERRORS',
	REESTART_GAME: 'REESTART_GAME',
	WIN_GAME: 'WIN_GAME'
};
